### ISSUE TITLE
Implementation of Microservice to calculate free spaces in a group

### ISSUE THREAD

**Issue by SnowArtz** [ISIS3510-202410-Team-13/Backend#14] opened 2024-04-06 23:06 UTC
Implementation of Microservice to calculate free spaces in a group.

**Comment by jsurrea** [comment] 2024-04-13 02:49
This is a duplicate of https://github.com/ISIS3510-202410-Team-13/Backend/issues/12

**Closed as completed** 2024-04-13 02:49 UTC
Labels: feature
