### ISSUE TITLE
Basic backend implementation. Set up the backend development environment and create mock endpoints for /friends and /groups, allowing the frontend to connect and receive mock data.

### ISSUE THREAD

**Issue by jdcastellanosb73** [ISIS3510-202410-Team-13/Backend#15] opened 2024-04-07 03:33 UTC
this feature should be implemented before [06/04]

**Comment by jsurrea** [comment] 2024-04-14 03:04
Hey @SnowArtz @iGotty! Can we close this issue? I think it is a duplicate of the PR you submitted

**Comment by SnowArtz** [comment] 2024-04-14 06:45
@jsurrea Yes, you are right, this is a duplicate of a PR that was already implemented and solve it. I close the issue,

**Closed as completed by SnowArtz** 2024-04-14 06:45 UTC
Labels: feature
